/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EGOOGLEANALYTICS_AUTODEFS_H
#define S3EGOOGLEANALYTICS_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_GOOGLEANALYTICS_NAME "s3eGoogleAnalytics"
#define S3E_EXT_GOOGLEANALYTICS_HASH 0x95f3a0d5

#endif /* !S3EGOOGLEANALYTICS_AUTODEFS_H */
