/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/*
 * This file contains the automatically generated loader-side
 * functions that form part of the extension.
 *
 * This file is awlays compiled into all loaders but compiles
 * to nothing if this extension is not enabled in the loader
 * at build time.
 */
#include "IwDebug.h"
#include "s3eGoogleAnalytics_autodefs.h"
#include "s3eEdk.h"
#include "s3eGoogleAnalytics.h"
//Declarations of Init and Term functions
extern s3eResult s3eGoogleAnalyticsInit();
extern void s3eGoogleAnalyticsTerminate();


// On platforms that use a seperate UI/OS thread we can autowrap functions
// here.   Note that we can't use the S3E_USE_OS_THREAD define since this
// code is oftern build standalone, outside the main loader build.
#if defined I3D_OS_IPHONE || defined I3D_OS_OSX || defined I3D_OS_LINUX || defined I3D_OS_WINDOWS

static s3eResult s3eGoogleAnalytics_Init_wrap(const char* ua_id, const char* screen_name)
{
    IwTrace(GOOGLEANALYTICS_VERBOSE, ("calling s3eGoogleAnalytics func on main thread: s3eGoogleAnalytics_Init"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)s3eGoogleAnalytics_Init, 2, ua_id, screen_name);
}

static s3eResult s3eGoogleAnalytics_Start_wrap()
{
    IwTrace(GOOGLEANALYTICS_VERBOSE, ("calling s3eGoogleAnalytics func on main thread: s3eGoogleAnalytics_Start"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)s3eGoogleAnalytics_Start, 0);
}

static s3eResult s3eGoogleAnalytics_End_wrap()
{
    IwTrace(GOOGLEANALYTICS_VERBOSE, ("calling s3eGoogleAnalytics func on main thread: s3eGoogleAnalytics_End"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)s3eGoogleAnalytics_End, 0);
}

#define s3eGoogleAnalytics_Init s3eGoogleAnalytics_Init_wrap
#define s3eGoogleAnalytics_Start s3eGoogleAnalytics_Start_wrap
#define s3eGoogleAnalytics_End s3eGoogleAnalytics_End_wrap

#endif

void s3eGoogleAnalyticsRegisterExt()
{
    /* fill in the function pointer struct for this extension */
    void* funcPtrs[3];
    funcPtrs[0] = (void*)s3eGoogleAnalytics_Init;
    funcPtrs[1] = (void*)s3eGoogleAnalytics_Start;
    funcPtrs[2] = (void*)s3eGoogleAnalytics_End;

    /*
     * Flags that specify the extension's use of locking and stackswitching
     */
    int flags[3] = { 0 };

    /*
     * Register the extension
     */
s3eEdkRegister("s3eGoogleAnalytics", funcPtrs, sizeof(funcPtrs), flags, s3eGoogleAnalyticsInit, s3eGoogleAnalyticsTerminate, 0);
}

#if !defined S3E_BUILD_S3ELOADER

#if defined S3E_EDK_USE_STATIC_INIT_ARRAY
int s3eGoogleAnalyticsStaticInit()
{
    void** p = g_StaticInitArray;
    void* end = p + g_StaticArrayLen;
    while (*p) p++;
    if (p < end)
        *p = (void*)&s3eGoogleAnalyticsRegisterExt;
    return 0;
}

int g_s3eGoogleAnalyticsVal = s3eGoogleAnalyticsStaticInit();

#elif defined S3E_EDK_USE_DLLS
S3E_EXTERN_C S3E_DLL_EXPORT void RegisterExt()
{
    s3eGoogleAnalyticsRegisterExt();
}
#endif

#endif
