/*
 * (C) 2001-2012 Marmalade. All Rights Reserved.
 *
 * This document is protected by copyright, and contains information
 * proprietary to Marmalade.
 *
 * This file consists of source code released by Marmalade under
 * the terms of the accompanying End User License Agreement (EULA).
 * Please do not use this program/source code before you have read the
 * EULA and have agreed to be bound by its terms.
 */
/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3E_EXT_GOOGLEANALYTICS_H
#define S3E_EXT_GOOGLEANALYTICS_H

#include <s3eTypes.h>
  
enum s3eGoogleAnalyticsLogLevel {
  s3eGoogleAnalyticsLogLevelNone = 0,
  s3eGoogleAnalyticsLogLevelError = 1,
  s3eGoogleAnalyticsLogLevelWarning = 2,
  s3eGoogleAnalyticsLogLevelInfo = 3,
  s3eGoogleAnalyticsLogLevelVerbose = 4
};
// \cond HIDDEN_DEFINES
S3E_BEGIN_C_DECL
// \endcond

/**
 * Returns S3E_TRUE if the GoogleAnalytics extension is available.
 */
s3eBool s3eGoogleAnalyticsAvailable();

void s3eGoogleAnalytics_SetScreenName(const char* screen_name);

void s3eGoogleAnalytics_SetUserID(const char* user_name);

void s3eGoogleAnalytics_SetLogLevel(s3eGoogleAnalyticsLogLevel level);

// \cond HIDDEN_DEFINES
S3E_END_C_DECL
// \endcond

#endif /* !S3E_EXT_GOOGLEANALYTICS_H */
